# Generated by Django 6.1.1 on 2026-09-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tax',
            name='type',
            field=models.CharField(blank=True, default='Other', max_length=30),
        ),
    ]
