# Generated by Django 6.1.1 on 2026-09-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_paymentmethod_options_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
