# Generated by Django 6.1.1 on 2026-09-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_category_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentstatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='deliverystatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentterm',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ptdastatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['-created_at']},
        ),
    ]
