# Generated by Django 6.1.1 on 2026-10-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_assignmentstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeExpenseHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('company_id', models.PositiveIntegerField(blank=True, help_text='Null = global default for all companies', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'income_expense_heads',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('company_id', 'entry_type', 'name')},
            },
        ),
    ]
