# Generated by Django 6.1.1 on 2026-10-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Other', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('customer', models.CharField(blank=True, default='—', max_length=255)),
                ('expiry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateField(blank=True, null=True)),
                ('renewals', models.PositiveIntegerField(default=0)),
                ('last_renewed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'renewals',
                'ordering': ['expiry_date'],
            },
        ),
    ]
