# Generated by Django 6.1.1 on 2026-09-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='department',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='employee',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
