# Generated by Django 6.1.1 on 2026-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_alter_assignment_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allocated_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
