# Generated by Django 6.1.1 on 2026-09-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderservice',
            options={'ordering': ['-created_at']},
        ),
    ]
