# Generated by Django 6.1.1 on 2026-09-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_delivery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer_confirmation',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
