# Generated by Django 6.1.1 on 2026-10-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=10)),
                ('date', models.DateField()),
                ('head', models.CharField(default='General Expense', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('subcategory', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_method', models.CharField(default='Cash', max_length=20)),
                ('bank_payment_type', models.CharField(blank=True, default='', max_length=20)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
