# Generated by Django 5.2.17 on 2026-09-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('lead_soft_ref', models.CharField(blank=True, help_text='Original Lead Soft reference', max_length=50)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order_status', models.CharField(default='Pending', max_length=20)),
                ('payment_status', models.CharField(default='Unpaid', max_length=20)),
                ('delivery_status', models.CharField(default='Pending', max_length=20)),
                ('sales_person', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
