# Generated by Django 6.1.1 on 2026-09-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
