# Generated by Django 6.1.1 on 2026-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
