# Generated by Django 5.2.17 on 2026-09-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTDATemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=50)),
                ('fields_config', models.JSONField(default=list, help_text='Array of field definitions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ptda_templates',
            },
        ),
        migrations.CreateModel(
            name='PTDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', models.JSONField(default=dict, help_text='Field values for this PTDA instance')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptdas', to='services.orderservice')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptda.ptdatemplate')),
            ],
            options={
                'db_table': 'ptdas',
            },
        ),
    ]
