# Generated by Django 6.1.1 on 2026-09-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='transactions_clientdetail',
        ),
        migrations.AlterModelTable(
            name='department',
            table='master_branch',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='master_staff',
        ),
    ]
