# Generated by Django 6.1.1 on 2026-09-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_table_alter_department_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customertype',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-created_at']},
        ),
    ]
