# Generated by Django 6.1.1 on 2026-09-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_employee_employee_code_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
