# Generated by Django 5.2.17 on 2026-09-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('orders', 'Orders'), ('ptda', 'PTDA'), ('assignments', 'Assignments'), ('deliveries', 'Deliveries'), ('finance', 'Finance')], max_length=50)),
                ('filters', models.JSONField(default=dict)),
                ('columns', models.JSONField(default=list)),
                ('format', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], default='pdf', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_configs',
            },
        ),
    ]
