# Generated by Django 6.1.1 on 2026-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentschedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan_stage',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
