# Generated by Django 6.1.1 on 2026-09-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_plan_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='name',
            field=models.CharField(blank=True, default='Payment Plan', max_length=200),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='plan_type',
            field=models.CharField(blank=True, default='Milestone', max_length=50),
        ),
    ]
